PryGymV/Models/Cruce.cs
using System.ComponentModel.DataAnnotations;

namespace PryGymV.Models
{
    public class Cruce
    {
        public string? Nombre { get; set; }

        public string? Apellido { get; set; }

        public float Peso { get; set; }

        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }

        public float? Resultado { get; set; }

        public string? Estado { get; set; }

        public int? UsuarioID {get; set; }


}
}

PryGymV/Models/Imc.cs
using System.ComponentModel.DataAnnotations;

namespace PryGymV.Models
{
    public class Imc
    {
        public int ImcID { get; set; }

        public int UsuarioID { get; set; }

        public float Estatura { get; set; }

        public float Peso { get; set; }

        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }

        public float? Resultado { get; set; }

        public string? Estado { get; set; }

        public virtual Usuario? Usuario { get; set; }
    }
}

PryGymV/Models/Numero.cs
namespace PryGymV.Models
{
    public class Numero
    {

        public int? Valor { get; set; }
        public string? NombreEjercicio { get; set; }
    }
}

PryGymV/Models/Ranking.cs
using System.ComponentModel.DataAnnotations;

namespace PryGymV.Models
{
    public class Ranking
    {
        public string? Nombre { get; set; }

        public string? Apellido { get; set; }

        public float Peso { get; set; }

        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }

        public float? Resultado { get; set; }

        public string? Estado { get; set; }

        public int? UsuarioID { get; set; }

        public int? Numero { get; set; }
        public string? NombreEjercicio { get; set; }

    }
}

PryGymV/Models/Rutina.cs
namespace PryGymV.Models
{
    public class Rutina
    {
        public string? Nombre { get; set; }
        public string? NombreEjercicio { get; set; }

        public string? Repeticiones { get; set; }

        public string? Estado { get; set; }

        public int EjercicioID { get; set; }

        public bool? Recomendado { get; set; }
    }
}

PryGymV/Controllers/ImcsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PryGymV.Data;
using PryGymV.Models;

namespace PryGymV.Controllers
{
    
    public class ImcsController : Controller
    {
        private readonly PryGymVContext _context;

        public ImcsController(PryGymVContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "cli, adm")]

        // GET: Imcs
        public async Task<IActionResult> Index()
        {
            var a = HttpContext.User.IsInRole("adm");
            var c = HttpContext.User.Identity.Name;

            if (a==true)
            {
                var pryGymVContext = _context.Imc.Include(i => i.Usuario);
                return View(await pryGymVContext.ToListAsync());
            }
            else
            {
                var b = (from u in _context.Usuario
                         join i in _context.Imc on u.UsuarioID equals i.UsuarioID
                         where u.Email == c
                         select i
                         );

                return View(await b.ToListAsync());
            }

            
        }

        [Authorize(Roles = "cli, adm")]

        // GET: Imcs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Imc == null)
            {
                return NotFound();
            }

            var imc = await _context.Imc
                .Include(i => i.Usuario)
                .FirstOrDefaultAsync(m => m.ImcID == id);
            if (imc == null)
            {
                return NotFound();
            }

            return View(imc);
        }

        [Authorize(Roles = "cli, adm")]

        // GET: Imcs/Create
        public IActionResult Create()
        {
            var a = HttpContext.User.IsInRole("adm");
            var c = HttpContext.User.Identity.Name;

            if (a == true)
            {
                ViewData["UsuarioID"] = new SelectList(_context.Usuario, "UsuarioID", "Nombre");  
            }
            return View();

        }

        // POST: Imcs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ImcID,UsuarioID,Estatura,Peso,Fecha,Resultado,Estado")] Imc imc)
        { 
            var a = HttpContext.User.IsInRole("adm");
            var c = HttpContext.User.Identity.Name;

            if (a == true)
            {

                float est = imc.Estatura;
                float est1 = est / 100;
                float pes = imc.Peso;
                double resul = (float)(pes / Math.Pow(est1, 2));

                imc.Resultado = (float)resul;

                imc.Estado = Estado((float)resul);
                if (ModelState.IsValid)
                {
                    _context.Add(imc);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["UsuarioID"] = new SelectList(_context.Usuario, "UsuarioID", "UsuarioID", imc.UsuarioID);
                return View(imc);
            }
            else
            {
                float est = imc.Estatura;
                float pes = imc.Peso;
                float est1 = est / 100;
                double resul = (float)(pes / Math.Pow(est1, 2));

                imc.Resultado = (float)resul;

                imc.Estado = Estado((float)resul);

                var b = (from u in _context.Usuario
                         where u.Email == c
                         select u).FirstOrDefault();
                imc.UsuarioID = b.UsuarioID;

                _context.Add(imc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }

        public string Estado(float resul)
        {

            if (resul < 18.5)
            {
                return "Bajo Peso";

            }
            else if (resul >= 18.5 && resul <= 24.9)
            {
                return "Peso Saludable";

            }
            else if (resul >= 25.0 && resul <= 29.9)
            {
                return "SobrePeso";
            }
            else
            {
                return "Obesidad";
            }

        }

        [Authorize(Roles = "cli, adm")]

        // GET: Imcs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || _context.Imc == null)
            {
                return NotFound();
            }

            var imc = await _context.Imc.FindAsync(id);
            if (imc == null)
            {
                return NotFound();
            }
            ViewData["UsuarioID"] = new SelectList(_context.Usuario, "UsuarioID", "UsuarioID", imc.UsuarioID);
            return View(imc);
        }


        [Authorize(Roles = "cli, adm")]

        // POST: Imcs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ImcID,UsuarioID,Estatura,Peso,Fecha,Resultado,Estado")] Imc imc)
        {
            if (id != imc.ImcID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(imc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImcExists(imc.ImcID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioID"] = new SelectList(_context.Usuario, "UsuarioID", "UsuarioID", imc.UsuarioID);
            return View(imc);
        }

        [Authorize(Roles = "cli, adm")]

        // GET: Imcs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Imc == null)
            {
                return NotFound();
            }

            var imc = await _context.Imc
                .Include(i => i.Usuario)
                .FirstOrDefaultAsync(m => m.ImcID == id);
            if (imc == null)
            {
                return NotFound();
            }

            return View(imc);
        }

        [Authorize(Roles = "cli, adm")]
        // POST: Imcs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Imc == null)
            {
                return Problem("Entity set 'PryGymVContext.Imc'  is null.");
            }
            var imc = await _context.Imc.FindAsync(id);
            if (imc != null)
            {
                _context.Imc.Remove(imc);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "adm")]

        public async Task<IActionResult> Cruce (string buscar, DateTime fechaini, DateTime fechafin)
        {

            var a = (from u in _context.Usuario
                     join i in _context.Imc on u.UsuarioID equals i.UsuarioID
                     where  (i.Fecha >= fechaini && i.Fecha <= fechafin) || (u.Nombre == buscar)
                     select new Cruce
                     {
                         UsuarioID = u.UsuarioID,
                         Nombre = u.Nombre,
                         Apellido = u.Apellido,
                         Peso = i.Peso,
                         Fecha = i.Fecha,
                         Resultado = i.Resultado,
                         Estado = i.Estado
                     }).OrderBy(u => u.Resultado).ToList();

            return View(a);
        }

        [Authorize(Roles = "adm")]

        public async Task<IActionResult> Rutina(int id)
        {

            var a = (from u in _context.Usuario
                     join e in _context.Ejercicio on u.UsuarioID equals e.UsuarioID
                     join i in _context.Imc on u.UsuarioID equals i.UsuarioID
                     where e.UsuarioID == id
                     select new Rutina
                     {
                         Nombre = u.Nombre,
                         NombreEjercicio = e.NombreEjercicio,
                         Repeticiones = e.Repeticiones,
                         Estado = i.Estado,
                         EjercicioID = e.EjercicioID,
                         Recomendado = e.Recomendado
                     }).ToList();

            return View(a);
        }

        [Authorize(Roles = "adm")]

        [HttpPost]
        public async Task<IActionResult> Agregar(int id)
        {

            var a = _context.Ejercicio.Where(e  => e.EjercicioID == id).FirstOrDefault();

            a.Recomendado = true;
            await _context.SaveChangesAsync();

            return RedirectToAction("Cruce");
        }

        public async Task<IActionResult> Ranking(int id,string buscar, DateTime fechaini, DateTime fechafin)
        {

            var a = (from u in _context.Usuario
                     join i in _context.Imc on u.UsuarioID equals i.UsuarioID

PryGymV/Controllers/RutinaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PryGymV.Data;
using PryGymV.Models;
using System.Data;

namespace PryGymV.Controllers
{
    [Authorize(Roles = "cli,adm")]
    public class RutinaController : Controller
    {
        
        private readonly PryGymVContext _context;

        public RutinaController(PryGymVContext context)
        {

            _context = context;
        }

        public IActionResult Recomendacion()
        {
            var a = (from u in _context.Usuario
                     join e in _context.Ejercicio on u.UsuarioID equals e.UsuarioID
                     where e.Recomendado == true
                     select new Rutina
                     {
                         NombreEjercicio = e.NombreEjercicio,
                         Repeticiones = e.Repeticiones
                     }).ToList();

            return View(a);
        }
    }
}

PryGymV/Views/Imcs/Create.cshtml
@model PryGymV.Models.Imc

@{
    ViewData["Title"] = "Indice de Masa Corporal";
}

<h1>Crear</h1>

<h4>Imc</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @{
                var a = Context.User.IsInRole("adm");
                @if (a == true)
                {
                    <div class="form-group">
                        <label asp-for="UsuarioID" class="control-label"></label>
                        <select asp-for="UsuarioID" class="form-control" asp-items="ViewBag.UsuarioID"></select>
                    </div>
                }
            }
            <div class="form-group">
                <label asp-for="Estatura" class="control-label"></label>
                <input asp-for="Estatura" class="form-control" />
                <span asp-validation-for="Estatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

PryGymV/Views/Imcs/Cruce.cshtml
@model List<PryGymV.Models.Cruce>


@{
    ViewData["Title"] = "Administracion";
}

<h1>Listado de Usuarios</h1>



<form asp-controller="Imcs" asp-action="Cruce">
    <p>
        Buscar: <input type="text" name="buscar" class="form-text" />
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark"/>
    </p>
</form>


<form asp-controller="Imcs" asp-action="Cruce">
    <p>
        Desde: <input type="date" name="fechaini" />
        Hasta: <input type="date" name="fechafin"/>
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark" />   
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Apellido
            </th>
            <th>
                Peso
            </th>
            <th>
                Fecha
            </th>
            <th>
                Resultado
            </th>
            <th>
                Estado
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Peso)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Resultado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>

                <td>
                    <form asp-controller="Imcs" asp-action="Rutina" asp-route-id="@item.UsuarioID">
                        <p>
                            <input type="submit" value="Ver rutina" class="btn btn-sm btn-dark" />
                        </p>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

PryGymV/Views/Imcs/Delete.cshtml
@model PryGymV.Models.Imc

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Imc</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estatura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estatura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Peso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Peso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resultado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resultado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.UsuarioID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ImcID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PryGymV/Views/Imcs/Details.cshtml
@model PryGymV.Models.Imc

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <h4>Imc</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estatura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estatura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Peso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Peso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resultado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resultado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.UsuarioID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ImcID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PryGymV/Views/Imcs/Edit.cshtml
@model PryGymV.Models.Imc

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Imc</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ImcID" />
            <div class="form-group">
                <label asp-for="UsuarioID" class="control-label"></label>
                <select asp-for="UsuarioID" class="form-control" asp-items="ViewBag.UsuarioID"></select>
                <span asp-validation-for="UsuarioID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estatura" class="control-label"></label>
                <input asp-for="Estatura" class="form-control" />
                <span asp-validation-for="Estatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PryGymV/Views/Imcs/Index.cshtml
@model IEnumerable<PryGymV.Models.Imc>

@{
    ViewData["Title"] = "IMC";
}

<h1>Indice de Masa Corporal</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Estatura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Peso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Resultado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Estatura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Peso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Resultado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.Nombre)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ImcID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ImcID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ImcID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PryGymV/Views/Imcs/Numero.cshtml
@model List<PryGymV.Models.Numero>


@{
    ViewData["Title"] = "Rutina";
}

<h1>Ranking de Ejercicios</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                Nombre del Ejercicio
            </th>
            <th>
                Valor
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreEjercicio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
            </tr>
        }
    </tbody>
</table>

PryGymV/Views/Imcs/Ranking.cshtml
@model List<PryGymV.Models.Ranking>


@{
    ViewData["Title"] = "Administracion";
}

<h1>Listado de Usuarios</h1>



@*<form asp-controller="Imcs" asp-action="Ranking">
    <p>
        Buscar: <input type="text" name="buscar" class="form-text" />
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark" />
    </p>
</form>*@


<form asp-controller="Imcs" asp-action="Ranking">
    <p>
        Desde: <input type="date" name="fechaini" />
        Hasta: <input type="date" name="fechafin" />
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Apellido
            </th>
            <th>
                Peso
            </th>
            <th>
                Fecha
            </th>
            <th>
                Resultado
            </th>
            <th>
                Estado
            </th>
            <th>
                Numero
            </th>
            <th>
                Nombre del ejercicio
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Peso)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Resultado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Numero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreEjercicio)
                </td>

                <td>
                    <form asp-controller="Imcs" asp-action="Numero" asp-route-id="@item.UsuarioID">
                        <p>
                            <input type="submit" value="Ver valores" class="btn btn-sm btn-dark" />
                        </p>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

PryGymV/Views/Imcs/Rutina.cshtml
@model List<PryGymV.Models.Rutina>


@{
    ViewData["Title"] = "Rutina";
}

<h1>Listado de Ejercicios</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                Usuario
            </th>
            <th>
                Nombre del Ejercicio
            </th>
            <th>
                Repeticiones
            </th>
            <th>
                Estado
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreEjercicio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Repeticiones)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>

                @if(item.Recomendado == false)
                {
                    <td>
                        <form asp-controller="Imcs" asp-action="Agregar" asp-route-id="@item.EjercicioID">
                            <p>
                                <input type="submit" value="Recomendar" class="btn btn-sm btn-dark" />
                            </p>
                        </form>
                    </td>
                }   
            </tr>
        }
    </tbody>
</table>